version: '3.8'

services:
  nexus_wear_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3009:3000'
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    command: yarn start:dev
    environment:
      PORT: 3000
    restart: always

